git clone https://github.com/dense-analysis/ale
git clone https://github.com/chrisbra/csv
git clone https://github.com/junegunn/goyo.vim
git clone https://github.com/davidhalter/jedi-vim
git clone https://github.com/nanotech/jellybeans.vim
git clone https://github.com/iamcco/markdown-preview.vim
git clone https://github.com/ryanoasis/nerd-fonts
git clone https://github.com/preservvim/nerdtree
git clone https://github.com/jalvesaq/nvim-r
git clone https://github.com/Townk/vim-autoclose
git clone https://github.com/Chiel92/vim-autoformat
git clone https://github.com/octol/vim-cpp-enhanced-highlight
git clone https://github.com/ryanoasis/vim-devicons
git clone https://github.com/tpope/vim-fugitive
git clone https://github.com/airblade/vim-gitgutter
git clone https://github.com/mxw/vim-jsx
git clone https://github.com/terryma/vim-multiple-cursors
git clone https://github.com/psliwka/vim-smoothie
git clone https://github.com/tpope/vim-surround
git clone https://github.com/lervag/vimtex
